[package]
name = "bitcoin-evm-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
evm-rs-emulator = "0.1.4"
generic-array = "1.1.0"
rand = "0.8.5"
rust-crypto = "^0.2"

[profile.release]
opt-level = 3
